### ISSUE TITLE
Open Resources

### ISSUE THREAD

**Issue by Lilian9** [Lilian9/Open_Connect_Kenya#7]
Glad that you are here!
I am working on a GitHub Webpage that will have Kenya's Open Resources in one place. If you have links to open resources such as open access, open data, open source, open education, open scholarships, individuals working within these landscapes etc for Kenya, please add them accordingly below.
Thanks

## **Proactive Individuals within _Open Landscape_**
If you regularly share resources on open research and development in any social media sites or there are people within your circle you think are doing exceptional work in their communities, please share with [Lilian](https://github.com/Lilian9/Open_Connect_Kenya/issues/12) the following details. Name, Twitter or any other social media handle (and indicate), your country and institution you are working in. We are developing list of [Open Champions](https://docs.google.com/spreadsheets/d/1r26K2cokqxracCXTwMs-XERocqSZff1nJJGO5RboT7g/edit#gid=0) who Open Connect Kenya users will be able to interact with easily.

## **Open Access Resources**
According to Jotham Milimo Wasike on an assessment of the status of Open Access (OA) resources in Kenyan university libraries in 2013, Kenya as a developing country is still at the intermediate stage of embracing OA. He then went ahead and iterated that the university libraries are among the forefront institutions helping in the adoption of OA for research, empowerment, education and information. Therefore, the following is a list of OA resources have been sourced from other institutions’ websites championing for Open: 

**- Journals:**
[Smart Water](https://doaj.org/toc/2198-2619)
[International Clinical Neuroscience Journal](https://doaj.org/toc/2383-2096) 
[New Prairie Press](https://newprairiepress.org/journals.html)  
[BioMed Central](https://newprairiepress.org/journals.html) 
[Springer Open](https://newprairiepress.org/journals.html) 
[DOAJ for Kenya](https://www.doaj.org/search?source=%7B%22query%22%3A%7B%22filtered%22%3A%7B%22filter%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22term%22%3A%7B%22_type%22%3A%22journal%22%7D%7D%2C%7B%22term%22%3A%7B%22index.country.exact%22%3A%22Kenya%22%7D%7D%5D%7D%7D%2C%22query%22%3A%7B%22query_string%22%3A%7B%22query%22%3A%22kenya%22%2C%22default_operator%22%3A%22AND%22%7D%7D%7D%7D%7D) 
[DOAJ for Africa](https://doaj.org/search?source=%7B%22query%22%3A%7B%22filtered%22%3A%7B%22filter%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22term%22%3A%7B%22_type%22%3A%22journal%22%7D%7D%5D%7D%7D%2C%22query%22%3A%7B%22query_string%22%3A%7B%22query%22%3A%22africa%22%2C%22default_operator%22%3A%22AND%22%7D%7D%7D%7D%2C%22from%22%3A20%7D) 
[Kenya Projects Organization](http://www.kenpro.org/list-of-open-access-journal-links/) 

**- Open Access Map**
[Open Access Map](http://www.openaccessmap.org/) is a tool allowing  users to conduct searches or obtain overviews of Open Access developments around the world. It as well allows OA champions to add your own projects and services to the Map.

**- Open Access Button**
[Open Access Button](https://openaccessbutton.org/) is a tool enabling librarians, scholars, and technologists and anyone really to access easily, legally and freely millions of articles. Their sources include all of the aggregated repositories in the world, hybrid articles, open access journals, and those on authors personal pages.

## **Open Data Resources**

[Unpaywall](http://unpaywall.org/)
[Kenya Open Data](http://www.opendata.go.ke/) 
[Open Data for Africa](https://kenya.opendataforafrica.org/) 
[eCitizen](https://www.ecitizen.go.ke/)
[Smart County](http://icta.go.ke/smart-county/)

## **Open Education Resources**
Massive Open Online Courses:
 - www.edx.org
-  www.coursera.org
-  www.udacity.com
-  www.stjegypt.com
-  www.edraak.org
-  www.venture-lab.org
-  www.education.10gen.com
-  www.openhpi.de
-  www.ocw.mit.edu
-  www.khanacademy.org
-  www.oli.cmu.edu
-  www.ck12.org
-  www.udemy.com
-  www.skillshare.com
-  www.codecademy.com
-  www.p2pu.org
-  www.myopencourses.com
-  www.saylor.org
-  www.nalandau.com
-  www.academicearth.org
-  www.youtube.com/education
-  www.phodphad.com
-  www.learntobe.org
-  www.floqq.com
-  www.learnerstv.com
-  http://www.coursetalk.org
-  https://lnkd.in/ddTRJ-m
-  https://lnkd.in/dzjUfdy
-  www.alison.com
-  https://www.classcentral.com/university/stanford
-  https://yali.state.gov/courses/
-  https://learndigital.withgoogle.com/digitalskills
-  www.openclassroom.com
- https://www.classcentral.com/university/harvard
- https://www.classcentral.com/institution/microsoft
- https://developer.ibm.com/digitalnation/africa/courses/
- https://www.classcentral.com/university/mit
- https://www.futurelearn.com/courses

## **Open Scholarships**
[The Africa Open Data Fellowship](https://www.developlocal.org/the-africa-open-data-fellowship-launched-in-four-african-countries/) 
[OpenCon](https://www.opencon2018.org/)
[eLife Innovation Sprint](https://sprint.elifesciences.org/) 
[Open Life Sciences](https://openlifesci.org/) 
[Teaching with the Carpentries](https://carpentries.org/teach/) 
[The Carpentries CarpentryCon](https://carpentrycon.org/)
[Mozilla Fellowships](https://foundation.mozilla.org/en/fellowships/) 
[csv, conf](https://csvconf.com/) 
[CODATA-RDA School of Research and Data Science](https://codata.org/initiatives/strategic-programme/research-data-science-summer-schools/) 

## **Institutions**
[Code for Africa](https://github.com/CodeForAfrica/) 
[The African Academy of Sciences](https://www.aasciences.africa/)  
[International Network for the Availability of Scientific Publications (INASP)](https://www.inasp.info/) 
[iHub](https://ihub.co.ke/) 
[Regional Centre For Mapping Resource For Development](https://www.rcmrd.org/) 
[SPARC Africa](https://sparcopen.org/people/sparc-africa/) 
[Kenya- EIFL](https://www.eifl.net/country/kenya) 
[African Institute for Development Policy (AFIDEP)](https://www.afidep.org/) 
[Agricultural Information Resource Centre](http://www.airc.go.ke/) 
[Academic Model Providing Access to Healthcare (AMPATH)](https://www.ampathkenya.org/) 
[International Livestock Research Institution (ILRI)](https://www.ilri.org/) 
[KEMRI- Wellcome Trust](https://kemri-wellcome.org/) 
Kenya Agricultural and Livestock Research Organization (KALRO)
[Kenya Forestry Research Institute (KEFRI)](https://www.kefri.org/) 
[Kenya Industrial Research Institute (KIRDI)](https://www.kirdi.go.ke/) 
[Kenya Medical Research Institute](https://www.kemri.org/) 
[Kenya Marine and Fisheries Research Institute](https://www.kmfri.co.ke/) 
[National Crime Research Centre](http://crimeresearch.go.ke/) 
[Pan African University Institute for Basic Sciences, Technology and Innovation (PAUSTI)](http://www.jkuat.ac.ke/pauisti/) 
[Tegemeo Institute of Agricultural Policy and Development](http://www.tegemeo.org/) 
[The International Centre of Insect Physiology and Ecology (ICIPE)](http://www.icipe.org/) 
[The World Agroforestry Centre (ICRAF)](http://www.worldagroforestry.org/) 
[Kenya National Library Services](https://www.knls.ac.ke/index.php/home) 
[University of Nairobi](https://www.uonbi.ac.ke/) 
[Kenyatta University](http://www.ku.ac.ke/) 
[Jomo Kenyatta University of Agriculture and Technology](http://www.jkuat.ac.ke/) 
[United States International University Africa (USIU)](https://www.usiu.ac.ke/) 
[Strathmore University](https://www.strathmore.edu/) 
[Pwani University](https://www.pu.ac.ke/) 
[OpenScienceKE](https://bioinfonet.github.io/OpenScienceKE/)
[African Open Science Platform (AOSP)](http://africanopenscience.org.za/)
[Africa Open Science and Hardware (Africa OSH)](http://africaosh.com/)

## **Kenya's Open Policies**
[Access to Information Act, 2016](https://www.cuk.ac.ke/wp-content/uploads/2018/04/Access-to-Information-ActNo31.pdf) 
[National ICT Policy](http://icta.go.ke/national-ict-policy/)
According to EIFL, Strathmore University (Nairobi) adopted its OA policy in 2011; Jomo Kenyatta University of Agriculture and Technology and University of Nairobi adopted OA policies in 2012; Kenyatta University adopted OA policies in 2013; Pwani University (in Kilifi) adopted OA policies in 2014, and Kirinyaga University College (which is a constituent college of Jomo Kenyatta University of Agriculture and Technology) adopted OA policies in 2015.

**Comment by Lilian9** [comment]
@Kipkurui I'm currently working on this. This just a copy paste from google doc. I'll organize it in coming days

**Comment by kipkurui** [comment]
This is a very useful resource @Lilian9 . Looks good. Have a look at https://github.com/BioinfoNet also. We have some resources, and some research available there.

**Comment by Lilian9** [comment]
> 
> 
> This is a very useful resource @Lilian9 . Looks good. Have a look at https://github.com/BioinfoNet also. We have some resources, and some research available there.

Will look at it and later on do an update to this!
