### ISSUE TITLE
Open Platform

### ISSUE THREAD

**Issue by Lilian9** [Lilian9/Open_Connect_Kenya#8]
- [x] Research on resources needed for creating and hosting such platform
        - Seek advice from friends
        - Do online research
- [x] Look for online resources
        - Free webpages
        - Paid for webpages
- [x] Reach out to friends in Open landscape to narrow down Task 1 ideas
- [x] Start working on the platform
- [ ] Launch the platform

**Comment by Lilian9** [comment]
@Kipkurui

**Comment by kipkurui** [comment]
Great! Could you link up some of the outputs? You could create a markdown document with online resources. Also, make use of lists to do. See below:

- [x] Research on resources needed for creating and hosting such platform- Done
- [x] Look for online resources- Done
- [ ] Reach out to friends in Open landscape to narrow down Task 1 ideas- Done
- [ ] Start working on the platform- Done
- [ ] Launch the platform- 4/26/2020
